{% set name = "topologicpy" %}
{% set version = "0.8.44" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/wassimj/topologicpy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fe5cfac3ce168ffe824ede1c1a2ca29cb1a10d441accb1e5ac5ea7ae260b43c8

build:
  noarch: python
  number: 0
  script: pip install . -v --no-deps --ignore-installed --no-build-isolation

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.4.1
    - numpy >=1.18.0
    - pandas
    - scikit-learn
    - tqdm
    - topologic-core >=7.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - topologicpy

about:
  home: https://topologic.app/
  license_family: AGPL
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: The python bindings for topologic
  description: |
    An AI-Powered Spatial Modelling and Analysis Software Library for Architecture, Engineering, and Construction.
  dev_url: https://github.com/wassimj/topologicpy

extra:
  recipe-maintainers:
    - Krande
